export const EDITORIAL_CAPABILITY = {
    INSPECT_ARTICLE: "inspect_article",
    INSPECT_LINKED_ARTICLES: "inspect_linked_articles",
    INSPECT_REVISIONS: "inspect_revisions",
    INSPECT_DRAFT: "inspect_draft",
    INSPECT_ARTIFACTS: "inspect_artifacts",
    INSPECT_PROPOSAL_SUMMARY: "inspect_proposal_summary",
    INSPECT_FACT_CHECKS: "inspect_fact_checks",
    INSPECT_PUBLISHING_GUIDANCE: "inspect_publishing_guidance",
    INSPECT_STYLE_CORPUS: "inspect_style_corpus",
    INSPECT_ARTICLE_STYLE_RULES: "inspect_article_style_rules",
    INSPECT_TRANSLATIONS: "inspect_translations",
    RENAME_ARTICLE: "rename_article",
    CHANGE_ARTICLE_LANGUAGE: "change_article_language",
    ASSIGN_PUBLISHING_PROFILE: "assign_publishing_profile",
    SET_ARTICLE_STYLE_RULES: "set_article_style_rules",
    ADD_REVISION_TO_STYLE_CORPUS: "add_revision_to_style_corpus",
    REBUILD_STYLE_PROFILE: "rebuild_style_profile",
    REJECT_TRANSLATION: "reject_translation",
    GENERATE_PROPOSAL: "generate_proposal",
    GENERATE_FINDING_CORRECTIONS: "generate_finding_corrections",
    FACT_CHECK: "fact_check",
    STYLE_REVIEW: "style_review",
    TRANSLATE: "translate",
} as const;

export type EditorialCapabilityId = typeof EDITORIAL_CAPABILITY[keyof typeof EDITORIAL_CAPABILITY];
